services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel

networks:
  laravel:

volumes:
  pg_data:
